### ISSUE TITLE
How to generate NUnit output file automatically?

### ISSUE THREAD

**Issue by vivek9591** [CharliePoole/nunit-results#12]
Hi,

I am using " nunit3-console nunit.test.csproj" to generate NUnit output file. Is it necessary to execute this command every time after build. Actually, I want one time configuration of this command. Is there any way to do it once and NUnit will generate output file automatically after build.

Thanks in advance!

**Comment by CharliePoole** [comment]
You have to run the tests in order to get output. Using the nunit3-console command manually is one way. Another way is to set up your IDE to run the command when you execute via F5.

This is a usage question, not an issue. What is more, it has nothing to do with the nunit-results project but with how to use nunit. Please use the nunit-discuss mail list or file nunit issues with the nunit project.
